export function getHtml(): string {
  return [
    "<!DOCTYPE html>",
    '<html lang="en">',
    "<head>",
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    "<title>Table App</title>",
    '<link rel="preconnect" href="https://fonts.googleapis.com">',
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
    '<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" rel="stylesheet">',
    "<style>",
    ":root {",
    "  --bg: #f8f9fa;",
    "  --card-bg: #ffffff;",
    "  --border: #e2e8f0;",
    "  --text: #1a202c;",
    "  --text-secondary: #64748b;",
    "  --primary: #2563eb;",
    "  --primary-hover: #1d4ed8;",
    "  --danger: #dc2626;",
    "  --danger-hover: #b91c1c;",
    "  --row-alt: #f8fafc;",
    "  --row-hover: #f1f5f9;",
    "  --success: #16a34a;",
    "  --shadow: 0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.06);",
    "}",
    "* { margin: 0; padding: 0; box-sizing: border-box; }",
    "body {",
    "  font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;",
    "  background: var(--bg);",
    "  color: var(--text);",
    "  line-height: 1.5;",
    "  min-height: 100vh;",
    "}",
    ".container {",
    "  max-width: 1200px;",
    "  margin: 0 auto;",
    "  padding: 32px 24px;",
    "}",
    ".toolbar {",
    "  display: flex;",
    "  justify-content: space-between;",
    "  align-items: center;",
    "  margin-bottom: 16px;",
    "}",
    ".toolbar h1 {",
    "  font-size: 20px;",
    "  font-weight: 600;",
    "}",
    ".toolbar-actions {",
    "  display: flex;",
    "  gap: 8px;",
    "}",
    ".btn {",
    "  display: inline-flex;",
    "  align-items: center;",
    "  justify-content: center;",
    "  min-height: 36px;",
    "  padding: 6px 16px;",
    "  border: 1px solid var(--border);",
    "  border-radius: 6px;",
    "  background: var(--card-bg);",
    "  color: var(--text);",
    "  font-family: inherit;",
    "  font-size: 13px;",
    "  font-weight: 500;",
    "  cursor: pointer;",
    "  transition: all 0.15s;",
    "}",
    ".btn:hover { background: var(--row-hover); }",
    ".btn-primary {",
    "  background: var(--primary);",
    "  color: #fff;",
    "  border-color: var(--primary);",
    "}",
    ".btn-primary:hover { background: var(--primary-hover); }",
    ".btn-danger {",
    "  background: var(--danger);",
    "  color: #fff;",
    "  border-color: var(--danger);",
    "}",
    ".btn-danger:hover { background: var(--danger-hover); }",
    ".btn-sm {",
    "  min-height: 30px;",
    "  padding: 4px 10px;",
    "  font-size: 12px;",
    "}",
    ".card {",
    "  background: var(--card-bg);",
    "  border-radius: 8px;",
    "  box-shadow: var(--shadow);",
    "  border: 1px solid var(--border);",
    "  overflow: hidden;",
    "}",
    ".table-wrap { overflow-x: auto; }",
    "table {",
    "  width: 100%;",
    "  border-collapse: collapse;",
    "  font-size: 13px;",
    "}",
    "th, td {",
    "  padding: 8px 12px;",
    "  text-align: left;",
    "  border-bottom: 1px solid var(--border);",
    "  white-space: nowrap;",
    "}",
    "th {",
    "  background: var(--bg);",
    "  font-weight: 600;",
    "  font-size: 12px;",
    "  text-transform: uppercase;",
    "  letter-spacing: 0.03em;",
    "  color: var(--text-secondary);",
    "  user-select: none;",
    "  position: sticky;",
    "  top: 0;",
    "}",
    "th.sortable { cursor: pointer; }",
    "th.sortable:hover { color: var(--primary); }",
    ".sort-indicator { margin-left: 4px; font-size: 10px; }",
    "tr:nth-child(even) td { background: var(--row-alt); }",
    "tr:hover td { background: var(--row-hover); }",
    ".filter-row th {",
    "  padding: 4px 8px;",
    "  background: var(--card-bg);",
    "}",
    ".filter-row input {",
    "  width: 100%;",
    "  min-height: 30px;",
    "  padding: 4px 8px;",
    "  border: 1px solid var(--border);",
    "  border-radius: 4px;",
    "  font-family: inherit;",
    "  font-size: 12px;",
    "  outline: none;",
    "}",
    ".filter-row input:focus { border-color: var(--primary); }",
    ".cell-value { cursor: pointer; min-height: 24px; display: block; padding: 2px 0; }",
    ".cell-value:hover { background: #edf2f7; border-radius: 3px; }",
    ".cell-input {",
    "  width: 100%;",
    "  min-height: 30px;",
    "  padding: 4px 6px;",
    "  border: 2px solid var(--primary);",
    "  border-radius: 4px;",
    "  font-family: inherit;",
    "  font-size: 13px;",
    "  outline: none;",
    "}",
    ".mono { font-family: 'SF Mono', 'Fira Code', monospace; }",
    ".actions-cell { white-space: nowrap; }",
    ".confirm-delete {",
    "  display: inline-flex;",
    "  gap: 4px;",
    "  align-items: center;",
    "}",
    ".pagination {",
    "  display: flex;",
    "  justify-content: space-between;",
    "  align-items: center;",
    "  padding: 12px 16px;",
    "  border-top: 1px solid var(--border);",
    "  font-size: 13px;",
    "  color: var(--text-secondary);",
    "}",
    ".pagination-controls {",
    "  display: flex;",
    "  gap: 8px;",
    "  align-items: center;",
    "}",
    ".page-size-select {",
    "  min-height: 30px;",
    "  padding: 4px 8px;",
    "  border: 1px solid var(--border);",
    "  border-radius: 4px;",
    "  font-family: inherit;",
    "  font-size: 13px;",
    "  background: var(--card-bg);",
    "}",
    ".error-msg {",
    "  background: #fef2f2;",
    "  border: 1px solid #fecaca;",
    "  color: var(--danger);",
    "  padding: 8px 16px;",
    "  border-radius: 6px;",
    "  margin-bottom: 12px;",
    "  font-size: 13px;",
    "  display: none;",
    "}",
    ".loading {",
    "  text-align: center;",
    "  padding: 24px;",
    "  color: var(--text-secondary);",
    "}",
    ".empty-state {",
    "  text-align: center;",
    "  padding: 48px 24px;",
    "  color: var(--text-secondary);",
    "}",
    "</style>",
    "</head>",
    "<body>",
    '<div class="container">',
    '<div class="toolbar">',
    "  <h1>Items</h1>",
    '  <div class="toolbar-actions">',
    '    <button class="btn" id="btn-export" aria-label="Export CSV">Export CSV</button>',
    '    <button class="btn btn-primary" id="btn-add" aria-label="Add new row">+ Add Row</button>',
    "  </div>",
    "</div>",
    '<div id="error-bar" class="error-msg"></div>',
    '<div class="card">',
    '  <div class="table-wrap">',
    "    <table>",
    '      <thead id="thead"></thead>',
    '      <tbody id="tbody"></tbody>',
    "    </table>",
    '    <div id="loading" class="loading">Loading...</div>',
    '    <div id="empty" class="empty-state" style="display:none;">No items found. Click &quot;+ Add Row&quot; to create one.</div>',
    "  </div>",
    '  <div class="pagination">',
    '    <div id="page-info"></div>',
    '    <div class="pagination-controls">',
    '      <label for="page-size">Rows:</label>',
    '      <select id="page-size" class="page-size-select" aria-label="Rows per page">',
    '        <option value="25">25</option>',
    '        <option value="50">50</option>',
    '        <option value="100">100</option>',
    "      </select>",
    '      <button class="btn btn-sm" id="btn-prev" aria-label="Previous page">Prev</button>',
    '      <span id="page-num"></span>',
    '      <button class="btn btn-sm" id="btn-next" aria-label="Next page">Next</button>',
    "    </div>",
    "  </div>",
    "</div>",
    "</div>",
    "<script>",
    "(function() {",
    '  var COLUMNS = [',
    '    { key: "name", label: "Name", type: "text" },',
    '    { key: "status", label: "Status", type: "text" },',
    '    { key: "category", label: "Category", type: "text" },',
    '    { key: "value", label: "Value", type: "number" },',
    '    { key: "notes", label: "Notes", type: "text" },',
    '    { key: "created_at", label: "Created", type: "readonly" },',
    '    { key: "updated_at", label: "Updated", type: "readonly" }',
    "  ];",
    "",
    "  var state = {",
    "    rows: [],",
    "    total: 0,",
    "    page: 1,",
    "    limit: 25,",
    '    sort: "id",',
    '    order: "desc",',
    "    filters: {},",
    "    adding: false,",
    "    editingCell: null,",
    "    deletingId: null",
    "  };",
    "",
    "  var filterTimers = {};",
    "",
    "  function $(id) { return document.getElementById(id); }",
    "",
    "  function showError(msg) {",
    '    var el = $("error-bar");',
    "    el.textContent = msg;",
    '    el.style.display = "block";',
    "    setTimeout(function() {",
    '      el.style.display = "none";',
    "    }, 5000);",
    "  }",
    "",
    "  function api(method, url, body) {",
    "    var opts = {",
    "      method: method,",
    '      headers: { "Content-Type": "application/json" }',
    "    };",
    "    if (body) { opts.body = JSON.stringify(body); }",
    "    return fetch(url, opts).then(function(r) {",
    "      return r.json().then(function(data) {",
    "        if (!r.ok) {",
    '          throw new Error(data.error || "Request failed");',
    "        }",
    "        return data;",
    "      });",
    "    });",
    "  }",
    "",
    "  function loadRows() {",
    '    $("loading").style.display = "block";',
    '    $("empty").style.display = "none";',
    "    var params = new URLSearchParams();",
    '    params.set("page", String(state.page));',
    '    params.set("limit", String(state.limit));',
    '    params.set("sort", state.sort);',
    '    params.set("order", state.order);',
    "    var keys = Object.keys(state.filters);",
    "    for (var i = 0; i < keys.length; i++) {",
    "      var k = keys[i];",
    "      if (state.filters[k]) {",
    '        params.set("filter_" + k, state.filters[k]);',
    "      }",
    "    }",
    '    fetch("/api/rows?" + params.toString())',
    "      .then(function(r) { return r.json(); })",
    "      .then(function(data) {",
    "        if (data.error) { showError(data.error); return; }",
    "        state.rows = data.rows;",
    "        state.total = data.total;",
    "        state.page = data.page;",
    "        state.limit = data.limit;",
    "        renderTable();",
    "      })",
    "      .catch(function(e) { showError(e.message); })",
    "      .finally(function() {",
    '        $("loading").style.display = "none";',
    "      });",
    "  }",
    "",
    "  function renderHeader() {",
    '    var thead = $("thead");',
    '    var headerRow = "<tr>";',
    "    for (var i = 0; i < COLUMNS.length; i++) {",
    "      var col = COLUMNS[i];",
    '      var sortInd = "";',
    "      if (state.sort === col.key) {",
    '        sortInd = \'<span class="sort-indicator">\' + (state.order === "asc" ? "\\u25B2" : "\\u25BC") + "</span>";',
    "      }",
    '      headerRow += \'<th class="sortable" data-col="\' + col.key + \'">\' + col.label + sortInd + "</th>";',
    "    }",
    '    headerRow += "<th>Actions</th></tr>";',
    "",
    '    var filterRow = \'<tr class="filter-row">\';',
    "    for (var j = 0; j < COLUMNS.length; j++) {",
    "      var c = COLUMNS[j];",
    '      filterRow += \'<th><input type="text" placeholder="Filter..." data-filter="\' + c.key + \'" aria-label="Filter \' + c.label + \'" value="\' + (state.filters[c.key] || "") + \'"></th>\';',
    "    }",
    '    filterRow += "<th></th></tr>";',
    "",
    "    thead.innerHTML = headerRow + filterRow;",
    "",
    '    var ths = thead.querySelectorAll("th.sortable");',
    "    for (var s = 0; s < ths.length; s++) {",
    '      ths[s].addEventListener("click", function(e) {',
    '        var col = this.getAttribute("data-col");',
    "        if (state.sort === col) {",
    '          state.order = state.order === "asc" ? "desc" : "asc";',
    "        } else {",
    "          state.sort = col;",
    '          state.order = "asc";',
    "        }",
    "        state.page = 1;",
    "        loadRows();",
    "      });",
    "    }",
    "",
    '    var inputs = thead.querySelectorAll("input[data-filter]");',
    "    for (var f = 0; f < inputs.length; f++) {",
    '      inputs[f].addEventListener("input", function() {',
    '        var key = this.getAttribute("data-filter");',
    "        var val = this.value;",
    "        if (filterTimers[key]) { clearTimeout(filterTimers[key]); }",
    "        filterTimers[key] = setTimeout(function() {",
    "          state.filters[key] = val;",
    "          state.page = 1;",
    "          loadRows();",
    "        }, 300);",
    "      });",
    "    }",
    "  }",
    "",
    "  function escapeHtml(str) {",
    '    var div = document.createElement("div");',
    "    div.textContent = str;",
    "    return div.innerHTML;",
    "  }",
    "",
    "  function renderTable() {",
    '    var tbody = $("tbody");',
    '    var html = "";',
    "",
    "    if (state.adding) {",
    '      html += "<tr>";',
    "      for (var a = 0; a < COLUMNS.length; a++) {",
    "        var col = COLUMNS[a];",
    '        if (col.type === "readonly") {',
    '          html += "<td>-</td>";',
    "        } else {",
    '          var inputType = col.type === "number" ? "number" : "text";',
    '          html += \'<td><input class="cell-input" type="\' + inputType + \'" data-new-col="\' + col.key + \'" aria-label="New \' + col.label + \'" placeholder="\' + col.label + \'"></td>\';',
    "        }",
    "      }",
    '      html += \'<td class="actions-cell"><button class="btn btn-sm btn-primary" id="save-new" aria-label="Save new row">Save</button> <button class="btn btn-sm" id="cancel-new" aria-label="Cancel adding">Cancel</button></td>\';',
    '      html += "</tr>";',
    "    }",
    "",
    "    if (state.rows.length === 0 && !state.adding) {",
    '      $("empty").style.display = "block";',
    "    } else {",
    '      $("empty").style.display = "none";',
    "    }",
    "",
    "    for (var i = 0; i < state.rows.length; i++) {",
    "      var row = state.rows[i];",
    '      html += \'<tr data-id="\' + row.id + \'">\';',
    "      for (var j = 0; j < COLUMNS.length; j++) {",
    "        var c = COLUMNS[j];",
    '        var val = row[c.key] != null ? String(row[c.key]) : "";',
    "        var isEditing = state.editingCell && state.editingCell.id === row.id && state.editingCell.key === c.key;",
    "",
    "        if (isEditing) {",
    '          var inpType = c.type === "number" ? "number" : "text";',
    '          html += \'<td><input class="cell-input editing-input" type="\' + inpType + \'" value="\' + escapeHtml(val) + \'" data-row-id="\' + row.id + \'" data-col="\' + c.key + \'" aria-label="Edit \' + c.label + \'"></td>\';',
    '        } else if (c.type === "readonly") {',
    '          html += "<td>" + escapeHtml(val) + "</td>";',
    "        } else {",
    '          var cls = c.type === "number" ? "cell-value mono" : "cell-value";',
    '          html += \'<td><span class="\' + cls + \'" data-row-id="\' + row.id + \'" data-col="\' + c.key + \'">\' + escapeHtml(val) + "</span></td>";',
    "        }",
    "      }",
    "",
    '      html += \'<td class="actions-cell">\';',
    "      if (state.deletingId === row.id) {",
    '        html += \'<span class="confirm-delete">Delete? <button class="btn btn-sm btn-danger" data-confirm-del="\' + row.id + \'" aria-label="Confirm delete">Yes</button> <button class="btn btn-sm" data-cancel-del="\' + row.id + \'" aria-label="Cancel delete">No</button></span>\';',
    "      } else {",
    '        html += \'<button class="btn btn-sm" data-del="\' + row.id + \'" aria-label="Delete row \' + row.id + \'">Delete</button>\';',
    "      }",
    '      html += "</td></tr>";',
    "    }",
    "",
    "    tbody.innerHTML = html;",
    "    renderPagination();",
    "    bindTableEvents();",
    "  }",
    "",
    "  function renderPagination() {",
    "    var totalPages = Math.max(1, Math.ceil(state.total / state.limit));",
    '    $("page-info").textContent = state.total + " total rows";',
    '    $("page-num").textContent = "Page " + state.page + " of " + totalPages;',
    '    $("btn-prev").disabled = state.page <= 1;',
    '    $("btn-next").disabled = state.page >= totalPages;',
    '    $("page-size").value = String(state.limit);',
    "  }",
    "",
    "  function bindTableEvents() {",
    '    var cells = document.querySelectorAll(".cell-value");',
    "    for (var i = 0; i < cells.length; i++) {",
    '      cells[i].addEventListener("click", function() {',
    "        state.editingCell = {",
    '          id: parseInt(this.getAttribute("data-row-id"), 10),',
    '          key: this.getAttribute("data-col")',
    "        };",
    "        renderTable();",
    '        var inp = document.querySelector(".editing-input");',
    "        if (inp) { inp.focus(); inp.select(); }",
    "      });",
    "    }",
    "",
    '    var editInputs = document.querySelectorAll(".editing-input");',
    "    for (var e = 0; e < editInputs.length; e++) {",
    '      editInputs[e].addEventListener("keydown", function(ev) {',
    '        if (ev.key === "Enter") { saveEdit(this); }',
    '        if (ev.key === "Escape") { state.editingCell = null; renderTable(); }',
    "      });",
    '      editInputs[e].addEventListener("blur", function() {',
    "        var self = this;",
    "        setTimeout(function() { saveEdit(self); }, 100);",
    "      });",
    "    }",
    "",
    '    var saveBtn = document.getElementById("save-new");',
    "    if (saveBtn) {",
    '      saveBtn.addEventListener("click", function() { saveNewRow(); });',
    "    }",
    '    var cancelBtn = document.getElementById("cancel-new");',
    "    if (cancelBtn) {",
    '      cancelBtn.addEventListener("click", function() { state.adding = false; renderTable(); });',
    "    }",
    "",
    '    var newInputs = document.querySelectorAll("input[data-new-col]");',
    "    for (var n = 0; n < newInputs.length; n++) {",
    '      newInputs[n].addEventListener("keydown", function(ev) {',
    '        if (ev.key === "Enter") { saveNewRow(); }',
    '        if (ev.key === "Escape") { state.adding = false; renderTable(); }',
    "      });",
    "    }",
    "",
    '    var delBtns = document.querySelectorAll("[data-del]");',
    "    for (var d = 0; d < delBtns.length; d++) {",
    '      delBtns[d].addEventListener("click", function() {',
    '        state.deletingId = parseInt(this.getAttribute("data-del"), 10);',
    "        renderTable();",
    "      });",
    "    }",
    '    var confirmBtns = document.querySelectorAll("[data-confirm-del]");',
    "    for (var cd = 0; cd < confirmBtns.length; cd++) {",
    '      confirmBtns[cd].addEventListener("click", function() {',
    '        var id = parseInt(this.getAttribute("data-confirm-del"), 10);',
    "        deleteRow(id);",
    "      });",
    "    }",
    '    var cancelDelBtns = document.querySelectorAll("[data-cancel-del]");',
    "    for (var cb = 0; cb < cancelDelBtns.length; cb++) {",
    '      cancelDelBtns[cb].addEventListener("click", function() {',
    "        state.deletingId = null;",
    "        renderTable();",
    "      });",
    "    }",
    "  }",
    "",
    "  function saveEdit(inputEl) {",
    "    if (!state.editingCell) return;",
    '    var rowId = parseInt(inputEl.getAttribute("data-row-id"), 10);',
    '    var col = inputEl.getAttribute("data-col");',
    "    var val = inputEl.value;",
    "",
    "    var colDef = null;",
    "    for (var i = 0; i < COLUMNS.length; i++) {",
    "      if (COLUMNS[i].key === col) { colDef = COLUMNS[i]; break; }",
    "    }",
    "",
    "    var body = {};",
    '    if (colDef && colDef.type === "number") {',
    "      body[col] = parseFloat(val) || 0;",
    "    } else {",
    "      body[col] = val;",
    "    }",
    "",
    "    state.editingCell = null;",
    '    api("PUT", "/api/rows/" + rowId, body)',
    "      .then(function() { loadRows(); })",
    "      .catch(function(e) { showError(e.message); loadRows(); });",
    "  }",
    "",
    "  function saveNewRow() {",
    "    var body = {};",
    '    var inputs = document.querySelectorAll("input[data-new-col]");',
    "    for (var i = 0; i < inputs.length; i++) {",
    '      var key = inputs[i].getAttribute("data-new-col");',
    "      var val = inputs[i].value;",
    "      for (var j = 0; j < COLUMNS.length; j++) {",
    '        if (COLUMNS[j].key === key && COLUMNS[j].type === "number") {',
    "          body[key] = parseFloat(val) || 0;",
    "          break;",
    "        } else if (COLUMNS[j].key === key) {",
    "          body[key] = val;",
    "          break;",
    "        }",
    "      }",
    "    }",
    "",
    '    if (!body.name || !String(body.name).trim()) {',
    '      showError("Name is required");',
    "      return;",
    "    }",
    "",
    "    state.adding = false;",
    '    api("POST", "/api/rows", body)',
    "      .then(function() { loadRows(); })",
    "      .catch(function(e) { showError(e.message); });",
    "  }",
    "",
    "  function deleteRow(id) {",
    "    state.deletingId = null;",
    '    api("DELETE", "/api/rows/" + id)',
    "      .then(function() { loadRows(); })",
    "      .catch(function(e) { showError(e.message); });",
    "  }",
    "",
    "  renderHeader();",
    "  loadRows();",
    "",
    '  $("btn-add").addEventListener("click", function() {',
    "    state.adding = true;",
    "    renderTable();",
    '    var firstInput = document.querySelector("input[data-new-col]");',
    "    if (firstInput) firstInput.focus();",
    "  });",
    "",
    '  $("btn-export").addEventListener("click", function() {',
    '    window.location.href = "/api/export/csv";',
    "  });",
    "",
    '  $("btn-prev").addEventListener("click", function() {',
    "    if (state.page > 1) { state.page--; loadRows(); }",
    "  });",
    "",
    '  $("btn-next").addEventListener("click", function() {',
    "    var totalPages = Math.ceil(state.total / state.limit);",
    "    if (state.page < totalPages) { state.page++; loadRows(); }",
    "  });",
    "",
    '  $("page-size").addEventListener("change", function() {',
    "    state.limit = parseInt(this.value, 10);",
    "    state.page = 1;",
    "    loadRows();",
    "  });",
    "",
    "})();",
    "</script>",
    "</body>",
    "</html>",
  ].join("\n");
}
